spring:
  application:
    name: online-shop-api

  datasource:
    url: jdbc:mysql://mysql:3306/online_shop_api_db?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root